### PR TITLE
Code Cleanup, remove all IDE issues (except 1). Remove "Options", 

### PR DESCRIPTION
**Pull request by paul1956**
unused imports. Remove extra NL's

## Summary
Code cleanup to comply with .Net code style
Describe your changes here.
Mostly formatting changes, except removal on 1 duplicate assignment 
Fixes #Issue_Number (if available)

### CODE REVIEW

**Review by tdykstra — APPROVED** [review]

**Comment by tdykstra** [comment]
@paul1956 One more request -- the code in the 5.0 project didn't get converted correctly because it used new C# 9 syntax for constructors (`MyClass myclass = new()`) -- when changed to `MyClass myclass = new Myclass()` it will convert.  I did OptionsDefaults.cs and QuotedNumbers.cs -- could you do the others?

**Comment by paul1956** [comment]
Yes tonight PST.

**Comment by tdykstra** [comment]
Same vbnotes branch

**Comment by tdykstra** [comment]
you'll have to pull the latest commit

**Comment by paul1956** [comment]
@tdykstra Not sure which converter you used but mine currently hands C#9 New() correctly I will update and do another PR

**Comment by tdykstra** [comment]
Great, thanks!  I was using the online telerik converter.

**Comment by paul1956** [comment]
@tdykstra I used mine and also converted As Something = New Something... to As New Something

**Pull request merged**
